apiVersion: v1
kind: Namespace
metadata:
  name: kyma-hello-world

---
apiVersion: v1
kind: Service
metadata:
  name: kyma-hello-world
  namespace: kyma-samples
  labels:
    app: kyma-hello-world
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 4004
  selector:
    app: kyma-hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyma-hello-world
  namespace: kyma-samples
  labels:
    app: kyma-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma-hello-world
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: kyma-hello-world
    spec: # pod spec
      containers:
        - image: ghcr.io/sap-samples/kyma-mtx-faq-backend:latest # image we pushed
          name: faq-backend
          imagePullPolicy: Always
          env:
            - name: SM_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: credentials
                  name: sm-credentials
            - name: VCAP_SERVICES
              value: >
                {
                      "xsuaa": [{
                        "label": "xsuaa",
                        "provider": null,
                        "plan": "broker",
                        "name": "reviews-xsuaa",
                        "tags": [
                          "xsuaa"
                        ],
                        "instance_name": "reviews-xsuaa",
                        "binding_name": null,
                        "credentials": {
                          "tenantmode": "$(xsuaa_tenantmode)",
                          "sburl": "$(xsuaa_sburl)",
                          "clientid": "$(xsuaa_clientid)",
                          "xsappname": "$(xsuaa_xsappname)",
                          "clientsecret":"$(xsuaa_clientsecret)",
                          "url": "$(xsuaa_url)",
                          "uaadomain": "$(xsuaa_uaadomain)",
                          "trustedclientidsuffix": "$(xsuaa_trustedclientidsuffix)",
                          "verificationkey": "$(xsuaa_verificationkey)",
                          "apiurl": "$(xsuaa_apiurl)",
                          "identityzone": "$(xsuaa_identityzone)",
                          "identityzoneid": "$(xsuaa_identityzoneid)",
                          "tenantid": "$(xsuaa_tenantid)",
                          "zoneid": "$(xsuaa_zoneid)"
                        },
                        "syslog_drain_url": null,
                        "volume_mounts": []
                      }],
                      "service-manager": [{
                        "binding_name": null,
                        "credentials": $(SM_CREDENTIALS),
                        "instance_name": "sm",
                        "label": "service-manager",
                        "name": "sm",
                        "plan": "container",
                        "provider": null,
                        "syslog_drain_url": null,
                        "tags": [],
                        "volume_mounts": []
                      }]
                    }
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: 4004
