apiVersion: v1
kind: Namespace
metadata:
  name: kyma-samples

---
apiVersion: v1
kind: Service
metadata:
  name: kyma-hello-world
  namespace: kyma-samples
  labels:
    app: kyma-hello-world
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: kyma-hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyma-hello-world
  namespace: kyma-samples
  labels:
    app: kyma-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma-hello-world
  template:
    metadata:
      labels:
        app: kyma-hello-world
    spec:
      containers:
        - image: docker.pkg.github.com/eikeb/kyma-hello-world/kyma-hello-world:latest
          name: kyma-hello-world
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: dockerconfigjson-github-com
